#!/usr/bin/env python3
"""Measure FundingPips Phase-1 pass speed from completed GoldBot chains.

This is a descriptive realized-window diagnostic, not an independent restart
simulation. It reuses the actual closed-deal sequence generated by the stateful
MT5 tester chains at the accepted 0.50% challenge risk. Rolling windows inherit
whatever strategy/controller state existed in the source run, so a hit-rate must
not be interpreted as an exact probability for a fresh challenge account.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import json
import math
import statistics
import sys
from collections import defaultdict
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGIME_ANALYZER = ROOT / "scripts/analyze-fundingpips-regime-instability.py"
MT5_TIME = "%Y.%m.%d %H:%M:%S"


class PassSpeedError(RuntimeError):
    """Raised when completed tester evidence cannot be reconciled safely."""


def load_regime_module():
    spec = importlib.util.spec_from_file_location(
        "fundingpips_regime_instability", REGIME_ANALYZER
    )
    if spec is None or spec.loader is None:
        raise PassSpeedError(f"cannot load {REGIME_ANALYZER}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


REGIME = load_regime_module()


def parse_time(value: object) -> datetime:
    try:
        return datetime.strptime(str(value), MT5_TIME)
    except ValueError as exc:
        raise PassSpeedError(f"invalid MT5 timestamp: {value!r}") from exc


def month_key(value: datetime) -> str:
    return value.strftime("%Y-%m")


def next_month(value: date) -> date:
    return date(value.year + (1 if value.month == 12 else 0), 1 if value.month == 12 else value.month + 1, 1)


def closed_balance_drawdown_pct(
    trades: list[dict[str, object]], initial_balance: float
) -> float:
    balance = peak = initial_balance
    worst = 0.0
    for row in trades:
        balance += float(row["profit"])
        peak = max(peak, balance)
        if peak > 0:
            worst = max(worst, (peak - balance) / peak * 100.0)
    return worst


def earliest_target_hit(
    trades: list[dict[str, object]], target_cash: float
) -> datetime | None:
    cumulative = 0.0
    for row in trades:
        cumulative += float(row["profit"])
        if cumulative + 0.005 >= target_cash:
            return parse_time(row["timestamp"])
    return None


def summarize_calendar_months(
    window: str,
    trades: list[dict[str, object]],
    initial_balance: float,
    target_cash: float,
) -> list[dict[str, object]]:
    grouped: dict[str, list[dict[str, object]]] = defaultdict(list)
    for row in trades:
        grouped[month_key(parse_time(row["timestamp"]))].append(row)

    output: list[dict[str, object]] = []
    for month, rows in sorted(grouped.items()):
        rows.sort(key=lambda row: (str(row["timestamp"]), str(row["deal"])))
        net = sum(float(row["profit"]) for row in rows)
        hit = earliest_target_hit(rows, target_cash)
        output.append(
            {
                "window": window,
                "month": month,
                "closed_trades": len(rows),
                "net_profit": round(net, 2),
                "return_pct": round(net / initial_balance * 100.0, 6),
                "target_cash": round(target_cash, 2),
                "target_hit": "yes" if hit is not None else "no",
                "target_hit_time": hit.strftime(MT5_TIME) if hit else "",
                "closed_balance_dd_pct": round(
                    closed_balance_drawdown_pct(rows, initial_balance), 6
                ),
            }
        )
    return output


def summarize_rolling_windows(
    source_window: str,
    trades: list[dict[str, object]],
    initial_balance: float,
    target_cash: float,
    horizon_days: int,
) -> list[dict[str, object]]:
    if not trades:
        return []
    ordered = sorted(
        trades, key=lambda row: (str(row["timestamp"]), str(row["deal"]))
    )
    first_day = parse_time(ordered[0]["timestamp"]).date()
    last_day = parse_time(ordered[-1]["timestamp"]).date()
    final_start = last_day - timedelta(days=horizon_days - 1)
    if final_start < first_day:
        return []

    output: list[dict[str, object]] = []
    start = first_day
    while start <= final_start:
        end_exclusive = start + timedelta(days=horizon_days)
        rows = [
            row
            for row in ordered
            if start <= parse_time(row["timestamp"]).date() < end_exclusive
        ]
        net = sum(float(row["profit"]) for row in rows)
        hit = earliest_target_hit(rows, target_cash)
        output.append(
            {
                "source_window": source_window,
                "horizon_days": horizon_days,
                "start_date": start.isoformat(),
                "end_date": (end_exclusive - timedelta(days=1)).isoformat(),
                "closed_trades": len(rows),
                "net_profit": round(net, 2),
                "return_pct": round(net / initial_balance * 100.0, 6),
                "target_hit": "yes" if hit is not None else "no",
                "days_to_target": (hit.date() - start).days + 1 if hit else "",
                "closed_balance_dd_pct": round(
                    closed_balance_drawdown_pct(rows, initial_balance), 6
                ),
            }
        )
        start += timedelta(days=1)
    return output


def quantile(values: list[float], fraction: float) -> float:
    if not values:
        return 0.0
    ordered = sorted(values)
    if len(ordered) == 1:
        return ordered[0]
    position = (len(ordered) - 1) * fraction
    lower = math.floor(position)
    upper = math.ceil(position)
    if lower == upper:
        return ordered[lower]
    weight = position - lower
    return ordered[lower] * (1.0 - weight) + ordered[upper] * weight


def summarize_horizon(rows: list[dict[str, object]], target_cash: float) -> dict[str, object]:
    profits = [float(row["net_profit"]) for row in rows]
    hits = [row for row in rows if row["target_hit"] == "yes"]
    days_to_target = [int(row["days_to_target"]) for row in hits]
    return {
        "eligible_windows": len(rows),
        "target_hit_windows": len(hits),
        "target_hit_rate_pct": round(len(hits) / len(rows) * 100.0, 6) if rows else 0.0,
        "target_cash": round(target_cash, 2),
        "average_net_profit": round(statistics.fmean(profits), 2) if profits else 0.0,
        "median_net_profit": round(statistics.median(profits), 2) if profits else 0.0,
        "p25_net_profit": round(quantile(profits, 0.25), 2),
        "p75_net_profit": round(quantile(profits, 0.75), 2),
        "best_net_profit": round(max(profits), 2) if profits else 0.0,
        "worst_net_profit": round(min(profits), 2) if profits else 0.0,
        "fastest_days_to_target": min(days_to_target) if days_to_target else None,
        "median_days_to_target_when_hit": (
            round(statistics.median(days_to_target), 2) if days_to_target else None
        ),
    }


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        raise PassSpeedError(f"refusing to write empty output: {path}")
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--window",
        nargs=2,
        action="append",
        metavar=("LABEL", "MANIFEST"),
        required=True,
    )
    parser.add_argument("--initial-balance", type=float, default=50000.0)
    parser.add_argument("--target-pct", type=float, default=8.0)
    parser.add_argument("--output-prefix", required=True, type=Path)
    args = parser.parse_args()

    if args.initial_balance <= 0 or args.target_pct <= 0:
        print("Pass-speed analysis FAILED: invalid balance/target", file=sys.stderr)
        return 2

    target_cash = args.initial_balance * args.target_pct / 100.0
    metadata: list[dict[str, object]] = []
    monthly_rows: list[dict[str, object]] = []
    rolling_rows: list[dict[str, object]] = []
    labels: set[str] = set()

    try:
        for label, raw_path in args.window:
            if label in labels:
                raise PassSpeedError(f"duplicate window label: {label}")
            labels.add(label)
            window_metadata, trades = REGIME.load_window(label, Path(raw_path))
            actual_initial = float(window_metadata["initial_balance"])
            if abs(actual_initial - args.initial_balance) > 0.01:
                raise PassSpeedError(
                    f"{label}: initial balance {actual_initial:.2f} != "
                    f"{args.initial_balance:.2f}"
                )
            metadata.append(window_metadata)
            monthly_rows.extend(
                summarize_calendar_months(
                    label, trades, args.initial_balance, target_cash
                )
            )
            for horizon in (30, 60):
                rolling_rows.extend(
                    summarize_rolling_windows(
                        label,
                        trades,
                        args.initial_balance,
                        target_cash,
                        horizon,
                    )
                )

        prefix = args.output_prefix
        prefix.parent.mkdir(parents=True, exist_ok=True)
        write_csv(prefix.with_name(prefix.name + ".months.csv"), monthly_rows)
        write_csv(prefix.with_name(prefix.name + ".rolling.csv"), rolling_rows)

        horizons = {
            str(horizon): summarize_horizon(
                [row for row in rolling_rows if int(row["horizon_days"]) == horizon],
                target_cash,
            )
            for horizon in (30, 60)
        }
        month_profits = [float(row["net_profit"]) for row in monthly_rows]
        payload = {
            "schema_version": 1,
            "created_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "purpose": "descriptive_realized_window_pass_speed_diagnostic",
            "initial_balance": args.initial_balance,
            "phase_1_target_pct": args.target_pct,
            "phase_1_target_cash": round(target_cash, 2),
            "accepted_challenge_risk_pct": 0.50,
            "windows": metadata,
            "calendar_month_summary": {
                "months": len(monthly_rows),
                "target_hit_months": sum(
                    row["target_hit"] == "yes" for row in monthly_rows
                ),
                "average_net_profit": round(statistics.fmean(month_profits), 2)
                if month_profits
                else 0.0,
                "median_net_profit": round(statistics.median(month_profits), 2)
                if month_profits
                else 0.0,
                "best_net_profit": round(max(month_profits), 2)
                if month_profits
                else 0.0,
                "worst_net_profit": round(min(month_profits), 2)
                if month_profits
                else 0.0,
            },
            "rolling_horizons": horizons,
            "limitations": [
                "Rolling windows are descriptive slices of realized stateful chains, not fresh-account restart simulations.",
                "Closed-balance drawdown does not replace MT5 floating-equity drawdown.",
                "Do not increase raw risk or loosen prop gates to force a 30/60-day pass.",
            ],
        }
        prefix.with_suffix(".json").write_text(json.dumps(payload, indent=2) + "\n")
    except (PassSpeedError, ValueError, KeyError) as exc:
        print(f"Pass-speed analysis FAILED: {exc}", file=sys.stderr)
        return 2

    print("FundingPips pass-speed diagnostic complete; no MT5 run was performed.")
    print(f"Outputs: {args.output_prefix}.months.csv")
    print(f"         {args.output_prefix}.rolling.csv")
    print(f"         {args.output_prefix}.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
